# Generated by Django 3.2.2 on 2021-07-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
    ]
